name: Package Module
description: Package Auriya module with ultra compression

outputs:
  zip_name:
    description: Name of the created zip file
    value: ${{ steps.package.outputs.zip_name }}
  version:
    description: Version from Cargo.toml
    value: ${{ steps.package.outputs.version }}
  version_code:
    description: Version code (total commits)
    value: ${{ steps.package.outputs.version_code }}

runs:
  using: composite
  steps:
    - name: Package Module
      id: package
      shell: bash
      run: |
        set -e
        
        BUILD_DIR="build/release"
        MODULE_DIR="module"
        TARGET_BIN="target/aarch64-linux-android/release/auriya"
        WEBUI_DIST="webui/dist"
        
        mkdir -p "$BUILD_DIR/module"
        cp -r "$MODULE_DIR"/* "$BUILD_DIR/module/"
        
        mkdir -p "$BUILD_DIR/module/system/bin"
        cp "$TARGET_BIN" "$BUILD_DIR/module/system/bin/"
        
        mkdir -p "$BUILD_DIR/module/webroot"
        cp -r "$WEBUI_DIST"/* "$BUILD_DIR/module/webroot/"
        
        cp settings.toml "$BUILD_DIR/module/"
        cp gamelist.toml "$BUILD_DIR/module/"
        
        # Get version from Cargo.toml
        VERSION=$(grep '^version = ' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
        COMMIT_HASH=$(git rev-parse --short HEAD)
        VERSION_CODE=$(git rev-list --count HEAD)
        
        # Update module.prop
        sed -i "s/^version=.*/version=${VERSION} (${VERSION_CODE}-${COMMIT_HASH}-release)/" "$BUILD_DIR/module/module.prop"
        sed -i "s/^versionCode=.*/versionCode=${VERSION_CODE}/" "$BUILD_DIR/module/module.prop"
        
        # Filename: auriya-1.0.1-10001-cc53e50-release.zip
        ZIP_NAME="auriya-${VERSION}-${VERSION_CODE}-${COMMIT_HASH}-release.zip"
        
        cd "$BUILD_DIR/module"
        7z a -tzip -mm=Deflate -mx=9 -mfb=258 -mpass=15 "../$ZIP_NAME" .
        cd -
        
        echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT
        
        ls -lh "$BUILD_DIR/$ZIP_NAME"
        echo "Created $ZIP_NAME"
