name: Telegram Notify
description: Send notification to Telegram

inputs:
  bot_token:
    description: Telegram Bot Token
    required: true
  chat_id:
    description: Telegram Chat ID
    required: true
  type:
    description: Notification type (start or complete)
    required: true
    default: complete
  zip_file:
    description: Path to zip file (for complete notification)
    required: false

runs:
  using: composite
  steps:
    - name: Send Notification
      shell: bash
      env:
        BOT_TOKEN: ${{ inputs.bot_token }}
        CHAT_ID: ${{ inputs.chat_id }}
        NOTIFY_TYPE: ${{ inputs.type }}
        ZIP_PATH: ${{ inputs.zip_file }}
        RUN_NUMBER: ${{ github.run_number }}
        COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
        WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%s)
        
        if [ "$NOTIFY_TYPE" = "start" ]; then
          MESSAGE=$(printf "<b>Auriya</b>\n#ci_%s\n<blockquote expandable>%s</blockquote>\n\n<a href=\"%s\">Commit</a>\n<a href=\"%s\">Workflow run</a>" "$RUN_NUMBER" "$COMMIT_MSG" "$COMMIT_URL" "$WORKFLOW_URL")
          curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
            -d chat_id="$CHAT_ID" \
            --data-urlencode "text=$MESSAGE" \
            -d parse_mode="HTML" \
            -d disable_web_page_preview="true"
        elif [ "$NOTIFY_TYPE" = "complete" ]; then
          if [ -z "$ZIP_PATH" ] || [ ! -f "$ZIP_PATH" ]; then
            echo "Zip file not found: $ZIP_PATH"
            exit 0
          fi
          CAPTION=$(printf "<b>Auriya</b> #ci_%s\n<blockquote expandable>%s</blockquote>\n\n<a href=\"%s\">Commit</a> | <a href=\"%s\">Workflow</a>" "$RUN_NUMBER" "$COMMIT_MSG" "$COMMIT_URL" "$WORKFLOW_URL")
          curl -F chat_id="$CHAT_ID" \
            -F document=@"$ZIP_PATH" \
            -F caption="$CAPTION" \
            -F parse_mode="HTML" \
            "https://api.telegram.org/bot$BOT_TOKEN/sendDocument"
        fi
